/**
 * Generate the preview's self-contained KaTeX stylesheet.
 *
 * Two deliberate transformations:
 *
 * 1. **Only woff2 is embedded**, as a data URI. The preview must typeset
 *    offline and must not depend on the frontend's hashed asset names, which
 *    change between Harness builds.
 * 2. **Every selector is scoped under `.lp-scope`** and every font family is
 *    renamed `LPKaTeX_*`. The transcript already renders KaTeX with its own
 *    stylesheet; a plugin that quietly redefined `.katex` or `KaTeX_Main` could
 *    change how answers look. It does not get to.
 *
 * Run: node scripts/gen-fonts.mjs
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const dist = join(here, '..', 'node_modules', 'katex', 'dist')
const outFile = join(here, '..', 'src', 'client', 'generated', 'katex-css.js')

/** Rewrite one `@font-face` block to a single embedded woff2 source. */
function embedFonts(css) {
  let inlined = 0
  const next = css.replace(
    /src:url\(fonts\/([A-Za-z0-9_.-]+)\.woff2\)\s*format\("woff2"\)(?:,url\(fonts\/[^)]+\)\s*format\("[^"]+"\))*/g,
    (_match, name) => {
      const bytes = readFileSync(join(dist, 'fonts', `${name}.woff2`))
      inlined += 1
      return `src:url(data:font/woff2;base64,${bytes.toString('base64')}) format("woff2")`
    },
  )
  if (inlined === 0) throw new Error('gen-fonts: no woff2 sources matched — did the KaTeX layout change?')
  return { css: next, inlined }
}

/** Prefix every non-`@font-face` selector so the preview cannot leak into the app. */
function scope(css, root) {
  return css.replace(/(^|})([^{}@]+)\{/g, (_match, lead, selector) => {
    const scoped = selector
      .split(',')
      .map((part) => `${root} ${part.trim()}`)
      .join(',')
    return `${lead}${scoped}{`
  })
}

const raw = readFileSync(join(dist, 'katex.min.css'), 'utf8')
const { css: embedded, inlined } = embedFonts(raw)
// Family renames keep the transcript's own `KaTeX_*` faces untouched.
const renamed = embedded.replace(/KaTeX_/g, 'LPKaTeX_')
const scoped = scope(renamed, '.lp-scope')

const banner = '/* Generated by scripts/gen-fonts.mjs — do not edit. */\n'
mkdirSync(dirname(outFile), { recursive: true })
writeFileSync(
  outFile,
  `${banner}export const KATEX_CSS = ${JSON.stringify(scoped)}\n`,
  'utf8',
)

const kb = (n) => `${(n / 1024).toFixed(0)} KB`
console.log(`gen-fonts: embedded ${inlined} woff2 faces → ${outFile}`)
console.log(`gen-fonts: stylesheet ${kb(raw.length)} → ${kb(scoped.length)} (scoped under .lp-scope)`)
